version: '3.9'

services:
  mongodb:
    image: mongo:${MONGO_VERSION}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    container_name: ${MONGO_CN_NAME}
